author = "Your Name"
name = "News Reporter Agent"
description = "Agent that reports current news from Amsterdam"
version = "1.0.0"
recreate_keys = true
kind = "agent"
debug_mode = false
debug_level = 1
monitoring = false
telemetry = true
num_history_sessions = 10
documentation_url = "https://docs.example.com/news-agent"

# Inline table for any extra metadata
extra_metadata = {}

# List of skills as inline tables
skills = [
  { name = "News Reporting", description = "Fetch and report current news", tags = ["news", "reporting"] }
]

[capabilities]
streaming = true
push_notifications = false
state_transition_history = false

[deployment]
url = "http://localhost:3773"
expose = true
protocol_version = "1.0.0"

